package collector

import (
	"time"

	"k8s-automation-dashboard/internal/models"
)

func (m *Manager) initDemoData() {
	now := time.Now()
	twoMinAgo := now.Add(-2 * time.Minute)
	fiveMinAgo := now.Add(-5 * time.Minute)

	m.healedCount = 14
	m.rollbackCount = 3
	m.scaleEvents = 28

	// Demo Pods for 01-pod-auto-healer
	m.cachedPods = []models.PodHealthInfo{
		{
			Name:            "payment-service-67b4f8d-x9q21",
			Namespace:       "production",
			Phase:           "Running",
			Node:            "node-pool-1-worker-01",
			Age:             "4d 12h",
			IsUnhealthy:     false,
			Restarts:        0,
			OwnerKind:       "Deployment",
			OwnerName:       "payment-service",
			EligibleToHeal:  true,
			HealAttempts:    0,
		},
		{
			Name:            "auth-gateway-55d8c7-4k8p2",
			Namespace:       "production",
			Phase:           "Running",
			Node:            "node-pool-1-worker-02",
			Age:             "18m",
			IsUnhealthy:     true,
			UnhealthyReason: "CrashLoopBackOff",
			Container:       "auth-proxy",
			Restarts:        7,
			OwnerKind:       "Deployment",
			OwnerName:       "auth-gateway",
			EligibleToHeal:  true,
			HealAttempts:    2,
			NextRetryIn:     "45s (exponential backoff)",
			LastRemediated:  &twoMinAgo,
		},
		{
			Name:            "analytics-worker-99ac2-z8t9q",
			Namespace:       "data-pipeline",
			Phase:           "Running",
			Node:            "node-pool-2-memory-01",
			Age:             "42m",
			IsUnhealthy:     true,
			UnhealthyReason: "OOMKilled",
			Container:       "spark-driver",
			Restarts:        4,
			OwnerKind:       "Deployment",
			OwnerName:       "analytics-worker",
			EligibleToHeal:  true,
			HealAttempts:    1,
			NextRetryIn:     "20s",
			LastRemediated:  &fiveMinAgo,
		},
		{
			Name:            "image-processor-84d9f-1lq9x",
			Namespace:       "media",
			Phase:           "Pending",
			Node:            "node-pool-1-worker-03",
			Age:             "12m",
			IsUnhealthy:     true,
			UnhealthyReason: "ImagePullBackOff",
			Container:       "resizer",
			Restarts:        0,
			OwnerKind:       "Deployment",
			OwnerName:       "image-processor",
			EligibleToHeal:  true,
			HealAttempts:    0,
		},
		{
			Name:            "redis-cache-0",
			Namespace:       "production",
			Phase:           "Running",
			Node:            "node-pool-1-worker-01",
			Age:             "12d",
			IsUnhealthy:     false,
			Restarts:        0,
			OwnerKind:       "StatefulSet",
			OwnerName:       "redis-cache",
			EligibleToHeal:  true,
			HealAttempts:    0,
		},
		{
			Name:            "db-migration-schema-v4-9xp9l",
			Namespace:       "database",
			Phase:           "Failed",
			Node:            "node-pool-1-worker-02",
			Age:             "1h 5m",
			IsUnhealthy:     true,
			UnhealthyReason: "Failed",
			Restarts:        0,
			OwnerKind:       "Job",
			OwnerName:       "db-migration-schema-v4",
			EligibleToHeal:  false, // Safety guard: Jobs are skipped
			HealAttempts:    0,
		},
	}

	// Demo Rollouts for 02-rollout-manager
	m.cachedRollouts = []models.RolloutInfo{
		{
			Name:              "order-api",
			Namespace:         "production",
			ReplicasDesired:   5,
			ReplicasUpdated:   5,
			ReplicasReady:     5,
			ReplicasAvailable: 5,
			CurrentRevision:   "4",
			PreviousRevision:  "3",
			IsStuck:           false,
			ProgressingStatus: "True",
			RollbackCount:     0,
			CanRollback:       true,
		},
		{
			Name:              "checkout-v2",
			Namespace:         "production",
			ReplicasDesired:   6,
			ReplicasUpdated:   2,
			ReplicasReady:     2,
			ReplicasAvailable: 2,
			CurrentRevision:   "5 (broken canary)",
			PreviousRevision:  "4 (healthy)",
			IsStuck:           true,
			StuckReason:       "ProgressDeadlineExceeded (Progressing=False)",
			ProgressingStatus: "False",
			RollbackCount:     1,
			LastRollbackTime:  &fiveMinAgo,
			CanRollback:       true,
		},
		{
			Name:              "notification-service",
			Namespace:         "notification",
			ReplicasDesired:   3,
			ReplicasUpdated:   3,
			ReplicasReady:     3,
			ReplicasAvailable: 3,
			CurrentRevision:   "2",
			PreviousRevision:  "1",
			IsStuck:           false,
			ProgressingStatus: "True",
			RollbackCount:     0,
			CanRollback:       true,
		},
	}

	// Demo Resource Optimizer data for 03-resource-optimizer
	m.cachedOptimizer = []models.ResourceRecommendation{
		{
			Key:            "production/auth-gateway/auth-proxy",
			Namespace:      "production",
			Pod:            "auth-gateway",
			Container:      "auth-proxy",
			SamplesCount:   120,
			CurrentCPUReq:  1000,
			CurrentCPULim:  2000,
			CurrentMemReq:  1024 * 1024 * 1024,
			CurrentMemLim:  2048 * 1024 * 1024,
			RecCPUReq:      250,
			RecCPULim:      600,
			RecMemReq:      384 * 1024 * 1024,
			RecMemLim:      768 * 1024 * 1024,
			CPUDrift:       "over",
			MemDrift:       "over",
			EstimatedWaste: "750m CPU / 640MiB RAM (75% waste)",
			UsageP50CPU:    210,
			UsageP90CPU:    540,
			UsageP50Mem:    340 * 1024 * 1024,
			UsageP90Mem:    680 * 1024 * 1024,
		},
		{
			Key:            "data-pipeline/analytics-worker/spark-driver",
			Namespace:      "data-pipeline",
			Pod:            "analytics-worker",
			Container:      "spark-driver",
			SamplesCount:   95,
			CurrentCPUReq:  500,
			CurrentCPULim:  1000,
			CurrentMemReq:  512 * 1024 * 1024,
			CurrentMemLim:  1024 * 1024 * 1024,
			RecCPUReq:      900,
			RecCPULim:      1800,
			RecMemReq:      1536 * 1024 * 1024,
			RecMemLim:      3072 * 1024 * 1024,
			CPUDrift:       "under",
			MemDrift:       "under",
			EstimatedWaste: "Throttling Risk (Requires +400m CPU / +1024MiB RAM)",
			UsageP50CPU:    820,
			UsageP90CPU:    1620,
			UsageP50Mem:    1400 * 1024 * 1024,
			UsageP90Mem:    2800 * 1024 * 1024,
		},
		{
			Key:            "production/payment-service/payment-service",
			Namespace:      "production",
			Pod:            "payment-service",
			Container:      "payment-service",
			SamplesCount:   240,
			CurrentCPUReq:  500,
			CurrentCPULim:  1000,
			CurrentMemReq:  512 * 1024 * 1024,
			CurrentMemLim:  1024 * 1024 * 1024,
			RecCPUReq:      480,
			RecCPULim:      950,
			RecMemReq:      490 * 1024 * 1024,
			RecMemLim:      980 * 1024 * 1024,
			CPUDrift:       "optimal",
			MemDrift:       "optimal",
			EstimatedWaste: "0m CPU (Optimal Sizing)",
			UsageP50CPU:    420,
			UsageP90CPU:    860,
			UsageP50Mem:    440 * 1024 * 1024,
			UsageP90Mem:    890 * 1024 * 1024,
		},
	}

	// Demo Autoscaler for 04-autoscaler
	m.cachedAutoscaler = models.AutoscalerStatus{
		Namespace:              "autoscaler-demo",
		Deployment:             "demo-app",
		CurrentReplicas:        4,
		DesiredReplicas:        6,
		MinReplicas:            1,
		MaxReplicas:            10,
		TargetCPUPercent:       50.0,
		CurrentCPUPercent:      72.4,
		Tolerance:              0.10,
		ScaleUpCooldownSec:     60,
		ScaleDownCooldownSec:   300,
		LastScaleDirection:     "up",
		LastScaleTime:          &twoMinAgo,
		NextScaleDownAllowedIn: "3m 42s",
		ScaleEventsCount:       28,
	}

	// Seed recent activity stream
	m.events = []models.Event{
		{
			ID:        "evt-01",
			Timestamp: now.Add(-1 * time.Minute),
			Module:    "scaler",
			Severity:  "info",
			Title:     "Scaling Up Replicas",
			Message:   "CPU Utilization at 72.4% (target: 50.0%) -> Scaled demo-app from 3 to 4 replicas",
			Namespace: "autoscaler-demo",
			Resource:  "demo-app",
		},
		{
			ID:        "evt-02",
			Timestamp: now.Add(-2 * time.Minute),
			Module:    "rollout",
			Severity:  "danger",
			Title:     "Stuck Rollout Detected",
			Message:   "Deployment checkout-v2 exceeded ProgressDeadlineExceeded condition -> Rollback target set to revision 4",
			Namespace: "production",
			Resource:  "checkout-v2",
		},
		{
			ID:        "evt-03",
			Timestamp: now.Add(-3 * time.Minute),
			Module:    "healer",
			Severity:  "warning",
			Title:     "CrashLoopBackOff Detected",
			Message:   "Pod auth-gateway-55d8c7-4k8p2 is crash looping. In-flight dedup guard scheduled exponential backoff remediation.",
			Namespace: "production",
			Resource:  "auth-gateway-55d8c7-4k8p2",
		},
		{
			ID:        "evt-04",
			Timestamp: now.Add(-4 * time.Minute),
			Module:    "optimizer",
			Severity:  "info",
			Title:     "Resource Recommendations Computed",
			Message:   "Analyzed 120 usage samples for auth-proxy container: 750m CPU over-provisioned.",
			Namespace: "production",
			Resource:  "auth-gateway",
		},
	}
}
